apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-xukz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-xukz
    app.kubernetes.io/part-of: integ-app-ilrg
  name: hacbs-test-project-xukz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-xukz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-xukz
    spec:
      containers:
      - image: quay.io/quay-or-not-to-quay/nbe-e2e-sxbb-tenant/integ-app-ilrg/hacbs-test-project-xukz@sha256:39c33f5e3739bfa7f3658b1cbe489f89b96ad60bc0c9c4a238a982ed7615f2de
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
